package io.apocalypse.calendar.domain;

/** 二十四节气稳定代码。 */
public enum SolarTerm {
  MINOR_COLD,
  MAJOR_COLD,
  START_OF_SPRING,
  RAIN_WATER,
  AWAKENING_OF_INSECTS,
  SPRING_EQUINOX,
  PURE_BRIGHTNESS,
  GRAIN_RAIN,
  START_OF_SUMMER,
  GRAIN_FULL,
  GRAIN_IN_EAR,
  SUMMER_SOLSTICE,
  MINOR_HEAT,
  MAJOR_HEAT,
  START_OF_AUTUMN,
  END_OF_HEAT,
  WHITE_DEW,
  AUTUMN_EQUINOX,
  COLD_DEW,
  FROST_DESCENT,
  START_OF_WINTER,
  MINOR_SNOW,
  MAJOR_SNOW,
  WINTER_SOLSTICE
}
