import {
  BookOpen,
  BookOpenText,
  CalendarCheck,
  CalendarClock,
  CalendarCog,
  CalendarDays,
  CalendarRange,
  CalendarSync,
  ClipboardList,
  FilePenLine,
  FileUp,
  LayoutDashboard,
  ListTree,
  LogIn,
  Monitor,
  MonitorDot,
  Network,
  ScrollText,
  Settings,
  Shapes,
  ShieldCheck,
  SlidersHorizontal,
  Users,
  Waypoints,
  type LucideIcon,
} from 'lucide-react'

export const MENU_ICON_NAMES = [
  'dashboard',
  'system',
  'setting',
  'user',
  'role',
  'peoples',
  'menu',
  'tree-table',
  'dept',
  'tree',
  'dict',
  'dictionary',
  'edit',
  'log',
  'logininfor',
  'form',
  'online',
  'monitor',
  'config',
  'calendar-days',
  'calendar-cog',
  'calendar-sync',
  'calendar-range',
  'calendar-clock',
  'calendar-check',
  'file-up',
  'waypoints',
] as const

const ICON_MAP: Record<(typeof MENU_ICON_NAMES)[number], LucideIcon> = {
  dashboard: LayoutDashboard,
  system: Settings,
  setting: Settings,
  user: Users,
  role: ShieldCheck,
  peoples: ShieldCheck,
  menu: BookOpen,
  'tree-table': ListTree,
  dept: Network,
  tree: Network,
  dict: BookOpen,
  dictionary: BookOpenText,
  edit: SlidersHorizontal,
  log: ScrollText,
  logininfor: LogIn,
  form: ClipboardList,
  online: MonitorDot,
  monitor: Monitor,
  config: FilePenLine,
  'calendar-days': CalendarDays,
  'calendar-cog': CalendarCog,
  'calendar-sync': CalendarSync,
  'calendar-range': CalendarRange,
  'calendar-clock': CalendarClock,
  'calendar-check': CalendarCheck,
  'file-up': FileUp,
  waypoints: Waypoints,
}

export function resolveMenuIcon(name: string | null): LucideIcon {
  const normalizedName = name?.trim().toLowerCase() ?? ''
  return ICON_MAP[normalizedName as keyof typeof ICON_MAP] ?? Shapes
}
